In [1]:
# importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
# importing the dataset
datasets = pd.read_csv('Data.csv')
datasets

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [17]:
# matrix of independent variables
X = datasets.iloc[:,:-1].values
df = pd.DataFrame(X)
df

0    1      2
0   France   44  72000
1    Spain   27  48000
2  Germany   30  54000
3    Spain   38  61000
4  Germany   40    NaN
5   France   35  58000
6    Spain  NaN  52000
7   France   48  79000
8  Germany   50  83000
9   France   37  67000

In [18]:
Y = datasets.iloc[:,3].values

In [21]:
df1 = pd.DataFrame(Y)
df1

0
0   No
1  Yes
2   No
3   No
4  Yes
5  Yes
6   No
7  Yes
8   No
9  Yes

In [31]:
# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [34]:
df

0        1        2
0   France       44    72000
1    Spain       27    48000
2  Germany       30    54000
3    Spain       38    61000
4  Germany       40  63777.8
5   France       35    58000
6    Spain  38.7778    52000
7   France       48    79000
8  Germany       50    83000
9   France       37    67000

In [46]:
# Encoding categorical variables
from sklearn.preprocessing import LabelEncoder as LE
le_X = LE()
X[:,0] = le_X.fit_transform(X[:,0])

In [47]:
from sklearn.preprocessing import OneHotEncoder as OHE
ohe = OHE(categorical_features = [0])
X = ohe.fit_transform(X).toarray()

In [48]:
X

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   4.40000000e+01,   7.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   2.70000000e+01,   4.80000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   3.00000000e+01,   5.40000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   3.80000000e+01,   6.10000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   4.00000000e+01,   6.37777778e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   3.50000000e+01,   5.80000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   3.87777778e+01,   5.20000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   4.80000000e+01,   7.90000000e+04],


In [50]:
le_Y = LE()
Y = le_Y.fit_transform(Y)

In [51]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [55]:
df1 = pd.DataFrame(Y)
df1.T

0  1  2  3  4  5  6  7  8  9
0  0  1  0  0  1  1  0  1  0  1

In [56]:
# Splitting the dataset into the training set and test set
from sklearn.model_selection import train_test_split as tts
X_train,X_test,Y_train,Y_test = tts(X,Y, test_size = 0.2, random_state = 0)

In [61]:
Y_test

array([0, 0], dtype=int64)

In [62]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler as SS
sc_X = SS()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [64]:
X_test

array([[ 1.        , -1.        ,  2.64575131, -0.77459667, -1.45882927,
        -0.90166297],
       [ 1.        , -1.        ,  2.64575131, -0.77459667,  1.98496442,
         2.13981082]])